// dsp_mac.v

// Generated using ACDS version 22.3 104

`timescale 1 ps / 1 ps
module dsp_mac (
		input  wire [7:0]  ay,         //         ay.ay
		input  wire [17:0] by,         //         by.by
		input  wire [7:0]  ax,         //         ax.ax
		input  wire [17:0] bx,         //         bx.bx
		input  wire [63:0] chainin,    //    chainin.chainin
		input  wire        accumulate, // accumulate.accumulate
		output wire [26:0] resulta,    //    resulta.resulta
		output wire [63:0] chainout,   //   chainout.chainout
		input  wire        clk0,       //       clk0.clk
		input  wire        clk1,       //       clk1.clk
		input  wire        clk2,       //       clk2.clk
		input  wire [2:0]  ena,        //        ena.ena
		input  wire        aclr0,      //      aclr0.reset
		input  wire        aclr1       //      aclr1.reset
	);

	dsp_mac_altera_a10_native_fixed_point_dsp_1910_4rwkd4q a10_native_fixed_point_dsp_0 (
		.ay         (ay),         //   input,   width = 8,         ay.ay
		.by         (by),         //   input,  width = 18,         by.by
		.ax         (ax),         //   input,   width = 8,         ax.ax
		.bx         (bx),         //   input,  width = 18,         bx.bx
		.chainin    (chainin),    //   input,  width = 64,    chainin.chainin
		.accumulate (accumulate), //   input,   width = 1, accumulate.accumulate
		.resulta    (resulta),    //  output,  width = 27,    resulta.resulta
		.chainout   (chainout),   //  output,  width = 64,   chainout.chainout
		.clk0       (clk0),       //   input,   width = 1,       clk0.clk
		.clk1       (clk1),       //   input,   width = 1,       clk1.clk
		.clk2       (clk2),       //   input,   width = 1,       clk2.clk
		.ena        (ena),        //   input,   width = 3,        ena.ena
		.aclr0      (aclr0),      //   input,   width = 1,      aclr0.reset
		.aclr1      (aclr1)       //   input,   width = 1,      aclr1.reset
	);

endmodule
