// dsp_mac_8bit_stratix.v

// Generated using ACDS version 22.3 104

`timescale 1 ps / 1 ps
module dsp_mac_8bit_stratix (
		input  wire [7:0]  ay,         //         ay.ay
		input  wire [7:0]  by,         //         by.by
		input  wire [7:0]  ax,         //         ax.ax
		input  wire [7:0]  bx,         //         bx.bx
		input  wire        accumulate, // accumulate.accumulate
		output wire [26:0] resulta,    //    resulta.resulta
		input  wire        clk0,       //       clk0.clk
		input  wire        clk1,       //       clk1.clk
		input  wire        clk2,       //       clk2.clk
		input  wire [2:0]  ena,        //        ena.ena
		input  wire        clr0,       //       clr0.reset
		input  wire        clr1        //       clr1.reset
	);

	dsp_mac_8bit_stratix_altera_s10_native_fixed_point_dsp_1910_z7ltzfa s10_native_fixed_point_dsp_0 (
		.ay         (ay),         //   input,   width = 8,         ay.ay
		.by         (by),         //   input,   width = 8,         by.by
		.ax         (ax),         //   input,   width = 8,         ax.ax
		.bx         (bx),         //   input,   width = 8,         bx.bx
		.accumulate (accumulate), //   input,   width = 1, accumulate.accumulate
		.resulta    (resulta),    //  output,  width = 27,    resulta.resulta
		.clk0       (clk0),       //   input,   width = 1,       clk0.clk
		.clk1       (clk1),       //   input,   width = 1,       clk1.clk
		.clk2       (clk2),       //   input,   width = 1,       clk2.clk
		.ena        (ena),        //   input,   width = 3,        ena.ena
		.clr0       (clr0),       //   input,   width = 1,       clr0.reset
		.clr1       (clr1)        //   input,   width = 1,       clr1.reset
	);

endmodule
